### ISSUE TITLE
Under which license is your code?

### ISSUE THREAD

**Issue by cit** [naoufal51/Orion#1]
Hi,

we would like to use some functions that you have written in another scientific project. Under which license is your code?

Thanks in advance!

**Comment by naoufal51** [comment]
Hello Florian,
Thanks for your interest and your remark, the license is MIT.
I would be glad to know more about your scientific project and how my code is beneficial to you.
Best,

**Comment by cit** [comment]
Thanks! If you give me a hint where I can find your email address, I will send you some information about our project.

Cheers!

**Comment by naoufal51** [comment]
No problem
My email is in my bio
Best,
