### ISSUE TITLE
disable antenna selection algorthim ?

### ISSUE THREAD

**Issue by Captital123** [naoufal51/Orion#4]
antenna selection means maping receive antenna to specific rf chain, i want to know that how to disable the antenna selection algorthim at receiver , so the signal from antenna A is fed to rf chain 1 , the signal from antenna B is fed to rf chain 2.

**Comment by SheepSui-coder** [comment]
Have u found the method? Is this necessary to disable the antenna selection?

**Comment by SheepSui-coder** [comment]
> Have u found the method? Is this necessary to disable the antenna selection?

Have u found the method? Is this necessary to disable the antenna selection?

**Comment by SheepSui-coder** [comment]
> antenna selection means maping receive antenna to specific rf chain, i want to know that how to disable the antenna selection algorthim at receiver , so the signal from antenna A is fed to rf chain 1 , the signal from antenna B is fed to rf chain 2.

Have u found the method? Is this necessary to disable the antenna selection?
